enum ActionKind {
    Walking,
    Idle,
    Jumping
}
namespace SpriteKind {
    export const Gap = SpriteKind.create()
}
controller.anyButton.onEvent(ControllerButtonEvent.Pressed, function () {
    mySprite.vy = -100
    animation.setAction(mySprite, ActionKind.Jumping)
    mySprite.startEffect(effects.rings, 300)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Gap, function (sprite, otherSprite) {
    if (otherSprite.right - sprite.left < 2) {
        info.changeScoreBy(1)
    }
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Projectile, function (sprite, otherSprite) {
    game.over(false)
})
let projectile: Sprite = null
let gapSprite: Sprite = null
let gapImage: Image = null
let bottomImage: Image = null
let topImage: Image = null
let gap = 0
let mySprite: Sprite = null
scene.setBackgroundColor(9)
info.setScore(0)
effects.blizzard.startScreenEffect()
mySprite = sprites.create(img`
    . . . . . . . . 6 6 6 6 6 6 6 . 
    . . . . . . . . 6 f f 6 f f 6 . 
    . . . . . . . . 6 f f 6 f f 6 . 
    . . . . . . . . 6 6 6 6 6 6 6 . 
    . . . . . . . . . . 6 6 6 . . . 
    . . . . . . . . . . 6 6 6 . . . 
    . . . . . . . . . . 6 6 6 . . . 
    . . . . 6 6 6 6 6 6 6 6 6 . . . 
    . . . . 6 6 6 6 6 6 6 6 6 . . . 
    . . . . 6 6 6 6 6 6 6 6 6 . . . 
    . . . . 6 6 6 6 6 6 6 6 6 . . . 
    . . . . 6 6 6 6 6 6 6 6 6 . . . 
    . . . . 6 6 6 6 6 6 6 6 6 . . . 
    . . . . 6 6 6 6 6 6 6 6 6 . . . 
    . . . . f f . f . f . f f . . . 
    . . . . f f . f . f . f f . . . 
    `, SpriteKind.Player)
mySprite.ay = 300
let anim = animation.createAnimation(ActionKind.Jumping, 25)
anim.addAnimationFrame(img`
    . . . . 8 8 8 8 8 8 8 8 8 . . . 
    8 8 8 8 8 8 8 8 8 8 8 8 8 8 6 6 
    6 6 8 6 8 6 6 6 8 6 8 6 8 6 8 6 
    6 8 8 6 8 6 8 6 8 6 8 6 8 6 8 6 
    6 6 8 6 8 6 6 6 8 6 6 6 8 6 6 6 
    f . . . . . . . . . . . . . f f 
    f f f f f . . . . f f f f f f . 
    . . . . f f f f f f . . . . . . 
    . . . . . . f f . . . . . . . . 
    . . . . . . f f . . . . . . . . 
    . . . . 6 6 6 6 6 6 . . . . . . 
    . . . . 6 f 6 6 f 6 . . . . . . 
    . . . . 6 6 6 6 6 6 . . . . . . 
    . . . . . . 6 6 . . . . . . . . 
    . . . . . . 6 6 6 6 6 6 6 . . . 
    . . . . . . f 6 6 6 6 6 f . . . 
    `)
anim.addAnimationFrame(img`
    . . . . 8 8 8 8 8 8 8 8 8 . . . 
    8 8 8 8 8 8 8 8 8 8 8 8 8 8 6 6 
    6 6 8 6 8 6 6 6 8 6 8 6 8 6 8 6 
    6 8 8 6 8 6 8 6 8 6 8 6 8 6 8 6 
    6 6 8 6 8 6 6 6 8 6 6 6 8 6 6 6 
    f . . . . . . . . . . . . . f f 
    f f f f f . . . . f f f f f f . 
    . . . . f f f f f f . . . . . . 
    . . . . . . f f . . . . . . . . 
    . . . . . . f f . . . . . . . . 
    . . . . 6 6 6 6 6 6 . . . . . . 
    . . . . 6 f 6 6 f 6 . . . . . . 
    . . . . 6 6 6 6 6 6 . . . . . . 
    . . . . . . 6 6 . . . . . . . . 
    . . . . . . 6 6 6 6 6 6 6 . . . 
    . . . . . . f 6 6 6 6 6 f . . . 
    `)
anim.addAnimationFrame(img`
    . . . . 8 8 8 8 8 8 8 8 8 . . . 
    8 8 8 8 8 8 8 8 8 8 8 8 8 8 6 6 
    6 6 8 6 8 6 6 6 8 6 8 6 8 6 8 6 
    6 8 8 6 8 6 8 6 8 6 8 6 8 6 8 6 
    6 6 8 6 8 6 6 6 8 6 6 6 8 6 6 6 
    f . . . . . . . . . . . . . f f 
    f f f f f . . . . f f f f f f . 
    . . . . f f f f f f . . . . . . 
    . . . . . . f f . . . . . . . . 
    . . . . . . f f . . . . . . . . 
    . . . . 6 6 6 6 6 6 . . . . . . 
    . . . . 6 f 6 6 f 6 . . . . . . 
    . . . . 6 6 6 6 6 6 . . . . . . 
    . . . . . . 6 6 . . . . . . . . 
    . . . . . . 6 6 6 6 6 6 6 . . . 
    . . . . . . f 6 6 6 6 6 f . . . 
    `)
anim.addAnimationFrame(img`
    . . . . 8 8 8 8 8 8 8 8 8 . . . 
    8 8 8 8 8 8 8 8 8 8 8 8 8 8 6 6 
    6 6 8 6 8 6 6 6 8 6 8 6 8 6 8 6 
    6 8 8 6 8 6 8 6 8 6 8 6 8 6 8 6 
    6 6 8 6 8 6 6 6 8 6 6 6 8 6 6 6 
    f . . . . . . . . . . . . . f f 
    f f f f f . . . . f f f f f f . 
    . . . . f f f f f f . . . . . . 
    . . . . . . f f . . . . . . . . 
    . . . . . . f f . . . . . . . . 
    . . . . 6 6 6 6 6 6 . . . . . . 
    . . . . 6 f 6 6 f 6 . . . . . . 
    . . . . 6 6 6 6 6 6 . . . . . . 
    . . . . . . 6 6 . . . . . . . . 
    . . . . . . 6 6 6 6 6 6 6 . . . 
    . . . . . . f 6 6 6 6 6 f . . . 
    `)
anim.addAnimationFrame(img`
    . . . . 8 8 8 8 8 8 8 8 8 . . . 
    8 8 8 8 8 8 8 8 8 8 8 8 8 8 6 6 
    6 6 8 6 8 6 6 6 8 6 8 6 8 6 8 6 
    6 8 8 6 8 6 8 6 8 6 8 6 8 6 8 6 
    6 6 8 6 8 6 6 6 8 6 6 6 8 6 6 6 
    f . . . . . . . . . . . . . f f 
    f f f f f . . . . f f f f f f . 
    . . . . f f f f f f . . . . . . 
    . . . . . . f f . . . . . . . . 
    . . . . . . f f . . . . . . . . 
    . . . . 6 6 6 6 6 6 . . . . . . 
    . . . . 6 f 6 6 f 6 . . . . . . 
    . . . . 6 6 6 6 6 6 . . . . . . 
    . . . . . . 6 6 . . . . . . . . 
    . . . . . . 6 6 6 6 6 6 6 . . . 
    . . . . . . f 6 6 6 6 6 f . . . 
    `)
anim.addAnimationFrame(img`
    . . . . 8 8 8 8 8 8 8 8 8 . . . 
    8 8 8 8 8 8 8 8 8 8 8 8 8 8 6 6 
    6 6 8 6 8 6 6 6 8 6 8 6 8 6 8 6 
    6 8 8 6 8 6 8 6 8 6 8 6 8 6 8 6 
    6 6 8 6 8 6 6 6 8 6 6 6 8 6 6 6 
    f . . . . . . . . . . . . . f f 
    f f f f f . . . . f f f f f f . 
    . . . . f f f f f f . . . . . . 
    . . . . . . f f . . . . . . . . 
    . . . . . . f f . . . . . . . . 
    . . . . 6 6 6 6 6 6 . . . . . . 
    . . . . 6 f 6 6 f 6 . . . . . . 
    . . . . 6 6 6 6 6 6 . . . . . . 
    . . . . . . 6 6 . . . . . . . . 
    . . . . . . 6 6 6 6 6 6 6 . . . 
    . . . . . . f 6 6 6 6 6 f . . . 
    `)
animation.attachAnimation(mySprite, anim)
game.onUpdate(function () {
    if (mySprite.vy > 0) {
        animation.setAction(mySprite, ActionKind.Idle)
    }
    if (mySprite.bottom > 120 || mySprite.top < 0) {
        game.over(false)
    }
})
game.onUpdateInterval(1500, function () {
    gap = randint(0, 3)
    if (gap == 0) {
        topImage = img`
            . . . . . . . . c c c c . . . . 
            . . . . c c c c c c c c c . . . 
            . . . c f c c a a a a c a c . . 
            . . c c f f f f a a a c a a c . 
            . . c c a f f c a a f f f a a c 
            . . c c a a a a b c f f f a a c 
            . c c c c a c c b a f c a a c c 
            c a f f c c c a b b 6 b b b c c 
            c a f f f f c c c 6 b b b a a c 
            c a a c f f c a 6 6 b b b a a c 
            c c b a a a a b 6 b b a b b a . 
            . c c b b b b b b b a c c b a . 
            . . c c c b c c c b a a b c . . 
            . . . . c b a c c b b b c . . . 
            . . . . c b b a a 6 b c . . . . 
            . . . . . . b 6 6 c c . . . . . 
            `
        bottomImage = img`
            . . . . . . c c c . . . . . . . 
            . . . . . a a a c c c . . . . . 
            . . . c a c f a a a a c . . . . 
            . . c a c f f f a f f a c . . . 
            . c c a c c f a a c f f a c . . 
            . a b a a c 6 a a c c f a c c c 
            . a b b b 6 a b b a a c a f f c 
            . . a b b a f f b b a a c f f c 
            c . a a a c c f c b a a c f a c 
            c c a a a c c a a a b b a c a c 
            a c a b b a a 6 a b b 6 b b c . 
            b a c b b b 6 b c . c c a c . . 
            b a c c a b b a c . . . . . . . 
            b b a c a b a a . . . . . . . . 
            a b 6 b b a c . . . . . . . . . 
            . a a b c . . . . . . . . . . . 
            `
    } else if (gap == 1) {
        topImage = img`
            .....6feeeeeeeeeef6.....
            ....6776eeeeeeeee676....
            ...6777666eeee6667776...
            ..6776ee67777777667776..
            ...668ee7768867788666...
            ......ee77eeee67ee......
            ......ee6eeeeee6ce......
            ......eefeeeeeeece......
            ......eeceeeeeeece......
            ......eeceeeeeeefe......
            ......eeceeeeeeefe......
            ......eeeeeeeeeefe......
            ......eeeeeeeeeece......
            .....6eeeeeeeeeece6.....
            ....6776eeeeeeeee676....
            ...6776666eeee6766776...
            ..6776ee77777777667776..
            ...668ce7768867788666...
            ......ce77eeee67ee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......beeeeeeeeeeb......
            .......beeeeeeeeb.......
            ........beeeeeeb........
            ........................
            ........................
            ........................
            `
        bottomImage = img`
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ..........bbbb..........
            ........bbddddbb........
            .......bddbbbbddb.......
            ......bdbbddddbbdb......
            .....bdbbdbbbbdbbdb.....
            .....bdbdbddddbdbdb.....
            .....cdbbdbbbbdbbdc.....
            .....cbdbbddddbbdbc.....
            .....efbddbbbbddbce.....
            .....eeffbddddbccee.....
            .....eeeeffcccceee......
            .....ceeeeeeeeeeee......
            .....ceeeeeeeeeeee......
            .....feeeeeeeeeeee......
            .....cceeeeeeeeeee......
            ......feeeeeeeeeee......
            .....6fceeeeeeeeee6.....
            ....6776eeeeeeeee676....
            ...6777666eeee6666776...
            ..67768e67766777667776..
            ...668ee7768867788666...
            ......ee77eeee77ecee....
            ......ee6eeeeee6eef.....
            ......eeeeeeeeeeeef.....
            ......eeeeeeeeeeeef.....
            ......eeeeeeeeeeecf.....
            ......ceeeeeeeeeecf.....
            ......ceeeeeeeeeeff.....
            ......feeeeeeeeeefe.....
            .....6feeeeeeeeeef6.....
            ....6776eeeeeeeee676....
            ...6777666eeee6667776...
            ..6776ee67777777667776..
            ...668ee7768867788666...
            ......ee77eeee67ee......
            ......ee6eeeeee6ce......
            ......eefeeeeeeece......
            ......eeceeeeeeece......
            ......eeceeeeeeefe......
            ......eeceeeeeeefe......
            ......eeeeeeeeeefe......
            ......eeeeeeeeeece......
            .....6eeeeeeeeeece6.....
            ....6776eeeeeeeee676....
            ...6776666eeee6766776...
            ..6776ee77777777667776..
            ...668ce7768867788666...
            ......ce77eeee67ee......
            ......ce6eeeeee6ee......
            `
    } else if (gap == 2) {
        topImage = img`
            .....6feeeeeeeeeef6.....
            ....6776eeeeeeeee676....
            ...6777666eeee6667776...
            ..6776ee67777777667776..
            ...668ee7768867788666...
            ......ee77eeee67eeee....
            ......ee6eeeeee6cef.....
            ......eeeeeeeeeeeef.....
            ......eeeeeeeeeeeef.....
            ......eeeeeeeeeeecf.....
            ......eeeeeeeeeeecf.....
            ......eeeeeeeeeeeff.....
            ......feeeeeeeeeefe.....
            .....6feeeeeeeeeef6.....
            ....6776eeeeeeeee676....
            ...6777666eeee6667776...
            ..6776ee67777777667776..
            ...668ee7768867788666...
            ......ee77eeee67ee......
            ......ee6eeeeee6ce......
            ......eefeeeeeeece......
            ......eeceeeeeeece......
            ......eeceeeeeeefe......
            ......eeceeeeeeefe......
            ......eeeeeeeeeefe......
            ......eeeeeeeeeece......
            .....6eeeeeeeeeece6.....
            ....6776eeeeeeeee676....
            ...6776666eeee6766776...
            ..6776ee77777777667776..
            ...668ce7768867788666...
            ......ce77eeee67ee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......beeeeeeeeeeb......
            .......beeeeeeeeb.......
            ........beeeeeeb........
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            `
        bottomImage = img`
            ........................
            ........................
            ........................
            ........................
            ..........bbbb..........
            ........bbddddbb........
            .......bddbbbbddb.......
            ......bdbbddddbbdb......
            .....bdbbdbbbbdbbdb.....
            .....bdbdbddddbdbdb.....
            .....cdbbdbbbbdbbdc.....
            .....cbdbbddddbbdbc.....
            .....efbddbbbbddbce.....
            .....eeffbddddbccee.....
            .....eeeeffcccceee......
            .....ceeeeeeeeeeee......
            .....ceeeeeeeeeeee......
            .....feeeeeeeeeeee......
            .....cceeeeeeeeeee......
            ......feeeeeeeeeee......
            .....6fceeeeeeeeee6.....
            ....6776eeeeeeeee676....
            ...6777666eeee6666776...
            ..67768e67766777667776..
            ...668ee7768867788666...
            ......ee77eeee77ecee....
            ......ee6eeeeee6eef.....
            ......eeeeeeeeeeeef.....
            ......eeeeeeeeeeeef.....
            ......eeeeeeeeeeecf.....
            ......ceeeeeeeeeecf.....
            ......ceeeeeeeeeeff.....
            ......feeeeeeeeeefe.....
            .....6feeeeeeeeeef6.....
            ....6776eeeeeeeee676....
            ...6777666eeee6667776...
            ..6776ee67777777667776..
            ...668ee7768867788666...
            ......ee77eeee67ee......
            ......ee6eeeeee6ce......
            `
    } else {
        topImage = img`
            .....6fceeeeeeeeee6.....
            ....6776eeeeeeeee676....
            ...6777666eeee6666776...
            ..67768e67766777667776..
            ...668ee7768867788666...
            ......ee77eeee77ecee....
            ......ee6eeeeee6eef.....
            ......eeeeeeeeeeeef.....
            ......eeeeeeeeeeeef.....
            ......eeeeeeeeeeecf.....
            ......ceeeeeeeeeecf.....
            ......ceeeeeeeeeeff.....
            ......feeeeeeeeeefe.....
            .....6feeeeeeeeeef6.....
            ....6776eeeeeeeee676....
            ...6777666eeee6667776...
            ..6776ee67777777667776..
            ...668ee7768867788666...
            ......ee77eeee67eeee....
            ......ee6eeeeee6cef.....
            ......eeeeeeeeeeeef.....
            ......eeeeeeeeeeeef.....
            ......eeeeeeeeeeecf.....
            ......eeeeeeeeeeecf.....
            ......eeeeeeeeeeeff.....
            ......feeeeeeeeeefe.....
            .....6feeeeeeeeeef6.....
            ....6776eeeeeeeee676....
            ...6777666eeee6667776...
            ..6776ee67777777667776..
            ...668ee7768867788666...
            ......ee77eeee67ee......
            ......ee6eeeeee6ce......
            ......eefeeeeeeece......
            ......eeceeeeeeece......
            ......eeceeeeeeefe......
            ......eeceeeeeeefe......
            ......eeeeeeeeeefe......
            ......eeeeeeeeeece......
            .....6eeeeeeeeeece6.....
            ....6776eeeeeeeee676....
            ...6776666eeee6766776...
            ..6776ee77777777667776..
            ...668ce7768867788666...
            ......ce77eeee67ee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......beeeeeeeeeeb......
            .......beeeeeeeeb.......
            ........beeeeeeb........
            ........................
            `
        bottomImage = img`
            ........................
            ..........bbbb..........
            ........bbddddbb........
            .......bddbbbbddb.......
            ......bdbbddddbbdb......
            .....bdbbdbbbbdbbdb.....
            .....bdbdbddddbdbdb.....
            .....cdbbdbbbbdbbdc.....
            .....cbdbbddddbbdbc.....
            .....efbddbbbbddbce.....
            .....eeffbddddbccee.....
            .....eeeeffcccceee......
            .....ceeeeeeeeeeee......
            .....ceeeeeeeeeeee......
            .....feeeeeeeeeeee......
            .....cceeeeeeeeeee......
            ......feeeeeeeeeee......
            .....6fceeeeeeeeee6.....
            ....6776eeeeeeeee676....
            ...6777666eeee6666776...
            ..67768e67766777667776..
            ...668ee7768867788666...
            ......ee77eeee77ecee....
            ......ee6eeeeee6eef.....
            `
    }
    gapImage = image.create(2, scene.screenHeight())
    gapImage.fill(1)
    gapSprite = sprites.create(gapImage, SpriteKind.Gap)
    gapSprite.setFlag(SpriteFlag.AutoDestroy, true)
    gapSprite.setFlag(SpriteFlag.Invisible, true)
    gapSprite.left = scene.screenWidth()
    gapSprite.vx = -45
    projectile = sprites.createProjectileFromSide(topImage, -45, 0)
    projectile.top = 0
    projectile = sprites.createProjectileFromSide(bottomImage, -45, 0)
    projectile.bottom = scene.screenHeight()
})
